"""Fixtures for ingestion tests."""
import os
import pytest
import tempfile

from src.ingestion.parsers.pdf_parser import PdfParser
from src.ingestion.parsers.text_parser import TextParser
from src.ingestion.chunkers.recursive_chunker import RecursiveChunker
from src.ingestion.chunkers.structural_chunker import StructuralChunker
from src.ingestion.chunkers.tabular_chunker import TabularChunker


@pytest.fixture
def pdf_parser():
    return PdfParser()


@pytest.fixture
def text_parser():
    return TextParser()


@pytest.fixture
def chunker():
    return RecursiveChunker(chunk_size=200, min_chunk_size=20)


@pytest.fixture
def sample_pdf(tmp_path):
    """Create a minimal valid PDF file for testing."""
    pdf_path = tmp_path / "test.pdf"
    # Minimal PDF content
    pdf_content = b"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 44 >>
stream
BT /F1 12 Tf 100 700 Td (Hello World) Tj ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000266 00000 n
0000000360 00000 n
trailer
<< /Size 6 /Root 1 0 R >>
startxref
441
%%EOF"""
    pdf_path.write_bytes(pdf_content)
    return str(pdf_path)


@pytest.fixture
def multi_page_pdf(tmp_path):
    """A multi-page PDF file (3 pages)."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "multi_page.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    for i in range(3):
        c.setFont("Helvetica", 12)
        c.drawString(72, 720, f"Page {i + 1}: This is the content of page {i + 1}.")
        c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def pdf_with_headings(tmp_path):
    """A PDF with section headings at different font sizes."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "headings.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    c.setFont("Helvetica", 16)
    c.drawString(72, 720, "Introduction")
    c.setFont("Helvetica", 11)
    c.drawString(72, 672, "This is the introduction section content.")
    c.setFont("Helvetica", 14)
    c.drawString(72, 612, "Section 1")
    c.setFont("Helvetica", 11)
    c.drawString(72, 582, "Content of section 1 goes here.")
    c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def empty_pdf(tmp_path):
    """A PDF with a blank page (no text)."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "empty.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def corrupted_pdf(tmp_path):
    """A file with .pdf extension but invalid/corrupted content."""
    path = tmp_path / "corrupted.pdf"
    path.write_bytes(b"This is not a valid PDF file - CORRUPTED CONTENT XYZ 12345")
    return str(path)


@pytest.fixture
def text_file(tmp_path):
    """A plain text file (wrong extension for PDF parser)."""
    path = tmp_path / "document.txt"
    path.write_text("This is plain text content, not a PDF.")
    return str(path)


@pytest.fixture
def unicode_pdf(tmp_path):
    """A PDF with unicode/special character content."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "unicode.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    c.setFont("Helvetica", 12)
    c.drawString(72, 720, "Unicode test: hello world with content")
    c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def pdf_with_headers_footers(tmp_path):
    """A PDF with header and footer text on each page."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "headers_footers.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    c.setFont("Helvetica", 8)
    c.drawString(72, 772, "COMPANY CONFIDENTIAL - INTERNAL USE ONLY")
    c.setFont("Helvetica", 12)
    c.drawString(72, 692, "Main document body content goes here on the page.")
    c.setFont("Helvetica", 8)
    c.drawString(72, 12, "Page 1 of 1 | Generated by System")
    c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def large_pdf(tmp_path):
    """A 100-page PDF for performance testing."""
    from reportlab.pdfgen import canvas as rl_canvas
    path = tmp_path / "large.pdf"
    c = rl_canvas.Canvas(str(path), pagesize=(612, 792))
    for i in range(100):
        c.setFont("Helvetica", 12)
        c.drawString(72, 720, f"Page {i + 1}. " + "Content word. " * 50)
        c.showPage()
    c.save()
    return str(path)


@pytest.fixture
def sample_txt(tmp_path):
    """A sample plain text file."""
    path = tmp_path / "sample.txt"
    path.write_text(
        "This is a sample plain text file.\nIt has multiple lines.\nLine three here.",
        encoding="utf-8",
    )
    return str(path)


@pytest.fixture
def sample_md(tmp_path):
    """A sample Markdown file with headings."""
    path = tmp_path / "sample.md"
    path.write_text(
        "# Introduction\n\nThis is the introduction.\n\n"
        "## Section 1\n\nContent for section 1.\n\n"
        "## Section 2\n\nContent for section 2.\n",
        encoding="utf-8",
    )
    return str(path)


@pytest.fixture
def md_with_code(tmp_path):
    """A Markdown file containing code blocks."""
    path = tmp_path / "code.md"
    path.write_text(
        "# Code Example\n\n"
        "```python\n"
        "def hello():\n"
        "    print('hello world')\n"
        "```\n\n"
        "After the code block.\n",
        encoding="utf-8",
    )
    return str(path)


@pytest.fixture
def empty_txt(tmp_path):
    """An empty text file."""
    path = tmp_path / "empty.txt"
    path.write_text("", encoding="utf-8")
    return str(path)


@pytest.fixture
def utf16_txt(tmp_path):
    """A UTF-16 encoded text file."""
    path = tmp_path / "utf16.txt"
    path.write_bytes("Hello UTF-16 world content here".encode("utf-16"))
    return str(path)
